# Use postgres/example user/password credentials
version: '3.1'

services:

  webapp:
    container_name: webapi_container
    build:
      context: ./GardeManger.WebApi
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - postgres-compose-network

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: GM_DBA
      POSTGRES_PASSWORD: K33pUrF00dS@fe
      POSTGRES_DB: GMDB
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  adminer:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test.test@test.com
      PGADMIN_DEFAULT_PASSWORD: K33pUrF00dS@fe
    restart: always
    ports:
      - 5555:80
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
