// <auto-generated />
using System;
using GardeManger.DatabaseAcces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GardeManger.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190623142005_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GardeManger.Entities.StockElement", b =>
                {
                    b.Property<int>("StockElementId")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan?>("ConservationPeriodAfterOpening");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("OpeningDate");

                    b.Property<DateTime>("PurchaseDate");

                    b.HasKey("StockElementId");

                    b.ToTable("StockElements");
                });
#pragma warning restore 612, 618
        }
    }
}
